# Construction of global states #

This Notebook shows how to Use the monogamy-module to solve the task outlined by the project description:

* As input data the program should take the number of registers of the gobal state denoted by $n$, a vector denoting their respective dimensions $\mathbf{d} = (d_1,d_2, \ldots, d_n)$ and an arbitrary number of marginal states on an arbitrary subset of $[n]$ (let us denote the marginal on $S \subset [n]$ by $\rho_S$.
* The program should determine whether the marginal states are compatible, and if so it should produce a valid global state $\rho_{12\ldots n}$.
* The program should be made publicly available on a website accompanied by a manual describing how to install it and use it. In particular, the input interface should be well-explained and user-friendly so that other researchers find it easy to use.

The function that fulfills the above requierements is called "construct_global_state" and this is how you use it:

In [1]:
import numpy as np
from monogamy import construct_global_state

We first show a simple three-qubit example. The quantum registers are $A, B$ and $C$, each of them is of dimension 2.

In [2]:
n = 3
d = [2,2,2]

We define the density matrices of the three marginals $\rho_{AB}, \rho_{AC}$ and $\rho_{BC}$.

In [3]:
rho_AB = np.array([[ 0.325, 0, 0, 0.15 ],
                   [ 0, 0.175,  0,  0  ],
                   [ 0,  0,  0.175, 0  ],
                   [ 0.15,  0, 0, 0.325]])
rho_AC = np.array([[ 0.325, 0, 0, 0.15 ],
                   [ 0, 0.175,  0,  0  ],
                   [ 0,  0,  0.175, 0  ],
                   [ 0.15,  0, 0, 0.325]])
rho_BC = np.array([[0.3, 0, 0, 0.1],
                   [0, 0.2, 0, 0  ],
                   [0,   0, 0.2, 0],
                   [0.1, 0, 0, 0.3]])
print(rho_AB)
print(rho_AC)
print(rho_BC)

[[ 0.325  0.     0.     0.15 ]
 [ 0.     0.175  0.     0.   ]
 [ 0.     0.     0.175  0.   ]
 [ 0.15   0.     0.     0.325]]
[[ 0.325  0.     0.     0.15 ]
 [ 0.     0.175  0.     0.   ]
 [ 0.     0.     0.175  0.   ]
 [ 0.15   0.     0.     0.325]]
[[ 0.3  0.   0.   0.1]
 [ 0.   0.2  0.   0. ]
 [ 0.   0.   0.2  0. ]
 [ 0.1  0.   0.   0.3]]


These matrices describe the marginals of the system. In order for monogamy to work, we have to give the module information about which of the systems are active and which are traced out. This happens with a bitmask, or list of booleans: each entry marked with "True" has been traced out. For example, in $\rho_{AB}$, the subsystem $C$ has been traced out. As $C$ is the third subsystem, we define the marginal als [False, False, True].

In [4]:
marg1 = (rho_AB, [False, False, True])
marg2 = (rho_AC, [False, True, False])
marg3 = (rho_BC, [False, True, False])

Now we have everything in place to call the main function:

In [5]:
(state, rho_g) = construct_global_state(n,d,[marg1,marg2,marg3])

The main function returns a state that describes, whether the marginalization was feasible or not. If it was feasible, the global state is given by rho_g:

In [6]:
print(state)

optimal


In [7]:
print(rho_g)

[[ 0.19375  0.       0.       0.       0.       0.0625   0.075    0.     ]
 [ 0.       0.13125  0.       0.       0.       0.       0.       0.075  ]
 [ 0.       0.       0.11875  0.       0.       0.       0.       0.0625 ]
 [ 0.       0.       0.       0.05625  0.       0.       0.       0.     ]
 [ 0.       0.       0.       0.       0.05625  0.       0.       0.     ]
 [ 0.0625   0.       0.       0.       0.       0.11875  0.       0.     ]
 [ 0.075    0.       0.       0.       0.       0.       0.13125  0.     ]
 [ 0.       0.075    0.0625   0.       0.       0.       0.       0.19375]]


Note, that you can use arbitrary combination of registers and states. A more involed example:

In [8]:
n = 4
d = [2,4,2,2]

In [9]:
rho_AB = np.array([[ 0.19375,  0,       0,       0,       0,       0.0625,   0.075,    0,     ],
                   [ 0,       0.13125,  0,       0,       0,       0,       0,       0.075,  ],
                   [ 0,       0,       0.11875,  0,       0,       0,       0,       0.0625, ],
                   [ 0,       0,       0,       0.05625, 0,       0,       0,       0,     ],
                   [ 0,       0,       0,       0,       0.05625,  0,       0,       0,     ],
                   [ 0.0625,   0,       0,       0,       0,       0.11875,  0,       0,     ],
                   [ 0.075,   0,       0,       0,       0,       0,       0.13125,  0,     ],
                   [ 0,       0.075,    0.0625,   0,       0,       0,       0,       0.19375]])
rho_ACD = np.array([[ 0.3,    0,     0,    0,    0,    0.125,  0.15,   0 ],
                    [ 0,    0.1, 0.076,    0,    0,    0,     0,     0.15 ],
                    [ 0,    0.076,  0.075, 0,    0,    0,     0,     0.125],
                    [ 0,    0,    0,     0.025,  0,     0,    0,    0,   ],
                    [ 0,    0,    0,     0,     0.025,  0,     0,    0,   ],
                    [ 0.125,  0,     0,     0,    0,     0.075,  0.076,  0   ],
                    [ 0.15,   0,     0,     0,    0,     0.076,  0.1,    0   ],
                    [ 0,     0.15,   0.125, 0,    0,     0,     0,     0.3  ]])

In [10]:
marg1 = (rho_AB, [False, False, True, True])
marg2 = (rho_ACD, [False, True, False, False])

In [11]:
(state, rho_2) = construct_global_state(n,d,[marg1,marg2])

In [12]:
print(state)

optimal


The density matrix of this system is quite large, so it is not easy to print. But this is just, how it is. It can't be helped.

In [13]:
print(rho_2)

[[  1.33518125e-01   6.50687842e-17   5.10537908e-17 ...,   2.85055281e-17
    2.60408629e-17   1.94478714e-18]
 [  6.50687842e-17   2.81270116e-02   2.23244347e-02 ...,  -7.07225787e-17
   -7.73163279e-17  -1.50206740e-17]
 [  5.10537908e-17   2.23244347e-02   2.29864590e-02 ...,  -5.93555578e-17
   -6.13659269e-17  -4.23608741e-17]
 ..., 
 [  2.85055281e-17  -7.07225787e-17  -5.93555578e-17 ...,   2.29864590e-02
    2.23244347e-02   6.82596666e-17]
 [  2.60408629e-17  -7.73163279e-17  -6.13659269e-17 ...,   2.23244347e-02
    2.81270116e-02   8.22343395e-17]
 [  1.94478714e-18  -1.50206740e-17  -4.23608741e-17 ...,   6.82596666e-17
    8.22343395e-17   1.33518125e-01]]


### Usability ###
If you use the function "construct_global_state" from the module, some sanity checks on your inputs are performed. In general, an Exceptioin will be thrown if you give inconsistent nonsense to the function. For example:

In [14]:
rho_AB = np.random.rand(4,4)
rho_AC = np.random.rand(4,4)
print(rho_AB)
print(rho_AC)

[[ 0.35389908  0.711865    0.30203867  0.32386859]
 [ 0.96191283  0.04239862  0.19758571  0.19413676]
 [ 0.84004009  0.40273331  0.87052893  0.19389434]
 [ 0.04169802  0.10983972  0.64278896  0.35303669]]
[[ 0.62864801  0.90309532  0.66959914  0.68972536]
 [ 0.60227811  0.83155922  0.16909896  0.16323362]
 [ 0.80688739  0.39117666  0.78362691  0.93538803]
 [ 0.95954545  0.8214042   0.80350399  0.35826368]]


In [15]:
n = 3
d = [2,2,2]
marg1 = (rho_AB, [False, False, True])
marg2 = (rho_AC, [False, True, False])
(state, rho_g) = construct_global_state(n,d,[marg1,marg2])

Exception: (<class 'ValueError'>, 'One of the given marginals is not a valid density operator!')

Also if you mess up with the markings for the marginals, it will be uncovered:

In [16]:
rho_AB = np.array([[ 0.325, 0, 0, 0.15 ],
                   [ 0, 0.175,  0,  0  ],
                   [ 0,  0,  0.175, 0  ],
                   [ 0.15,  0, 0, 0.325]])
rho_AC = np.array([[ 0.325, 0, 0, 0.15 ],
                   [ 0, 0.175,  0,  0  ],
                   [ 0,  0,  0.175, 0  ],
                   [ 0.15,  0, 0, 0.325]])
rho_BC = np.array([[0.3, 0, 0, 0.1],
                   [0, 0.2, 0, 0  ],
                   [0,   0, 0.2, 0],
                   [0.1, 0, 0, 0.3]])
print(rho_AB)
print(rho_AC)
print(rho_BC)

[[ 0.325  0.     0.     0.15 ]
 [ 0.     0.175  0.     0.   ]
 [ 0.     0.     0.175  0.   ]
 [ 0.15   0.     0.     0.325]]
[[ 0.325  0.     0.     0.15 ]
 [ 0.     0.175  0.     0.   ]
 [ 0.     0.     0.175  0.   ]
 [ 0.15   0.     0.     0.325]]
[[ 0.3  0.   0.   0.1]
 [ 0.   0.2  0.   0. ]
 [ 0.   0.   0.2  0. ]
 [ 0.1  0.   0.   0.3]]


In [17]:
n = 3
d = [2,2,2]
#marg1 = (rho_AB, [False, False, True]) # correct
marg1 = (rho_AB, [True, True, False]) # wrong
marg2 = (rho_AC, [False, True, False])
marg2 = (rho_BC, [True, False, False])
(state, rho_g) = construct_global_state(n,d,[marg1,marg2])

Exception: (<class 'ValueError'>, 'The dimensions of the marginal with the traced out parameters do not match')

If you use the separate functions of the monogamy module (as shown in the [next example](mono.ipynb), you have to take care of sanity checks by yourself, as in this case we assume you know what you do and do not feed in wrong inputs.

### Precision and Numerical stability ###
The monogamy module uses the Eigenvalue decomposition algorithms from NumPy, which are top-notch. However, ill-conditioned matrices might still introduce numerical errors to the process. As a consequence, all checks in monogamy are subject to a certain precision. This precision is $10^{-4}$ by default, but can be adjusted by the ftol keyword in most function calls.

If you experience problems, it might be worth to calibrate this parameter. Here is an example: at the beginning of this example we computed rho_g:

In [18]:
print(rho_g)

[[ 0.19375  0.       0.       0.       0.       0.0625   0.075    0.     ]
 [ 0.       0.13125  0.       0.       0.       0.       0.       0.075  ]
 [ 0.       0.       0.11875  0.       0.       0.       0.       0.0625 ]
 [ 0.       0.       0.       0.05625  0.       0.       0.       0.     ]
 [ 0.       0.       0.       0.       0.05625  0.       0.       0.     ]
 [ 0.0625   0.       0.       0.       0.       0.11875  0.       0.     ]
 [ 0.075    0.       0.       0.       0.       0.       0.13125  0.     ]
 [ 0.       0.075    0.0625   0.       0.       0.       0.       0.19375]]


Also the print-command is subject to a certain precision. If you evaluate the trace of this matrix closely, you will see that it is not exactly one:

In [19]:
print(np.matrix.trace(rho_g))

0.999999999929


The following function of the monogamy module checks if a matrix is a valid density operator. If we set the tolerance to 0, this matrix will fail the test:

In [20]:
from monogamy import is_density_operator
is_density_operator(rho_g, ftol=0)

False

Consequently, we have to adjust the tolerance in order for this matrix to pass as a density operator:

In [21]:
print(is_density_operator(rho_g, ftol=10e-20))
print(is_density_operator(rho_g, ftol=10e-10))
print(is_density_operator(rho_g, ftol=10e-4))

False
False
True
